# Generated by Django 6.0.5 on 2026-06-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediapost',
            name='extension',
            field=models.CharField(blank=True, max_length=10, verbose_name='расширение'),
        ),
    ]
